In [1]:
## data preprocessing 1

# specific format
# numeric data
# scaling the data

# data preprocessing
# imputing missing value
# handling categorical data
# scaling of data
# normalizarion 
# feature selection

In [2]:
# 1. imputing missing values
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {'one' : pd.Series([1,2,5],index=['a','b','e']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}

table = pd.DataFrame(data)

print(table)

# by default always convert to df any data

   one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN

In [11]:
table.isnull()

     one    two
a  False  False
b  False  False
c   True  False
d   True  False
e  False   True

In [ ]:
table.isnull().any()
#  gives column name who have null values

In [19]:
null_val = table.isnull().sum()
type(null_val)

pandas.Series

In [31]:
missing_pct = (null_val/len(table))*100
missing_pct

# how much of a col is not null

one    40.0
two    20.0
dtype: float64

In [8]:
# null handling
# using simple imputer

from sklearn.impute import SimpleImputer

si1 = SimpleImputer(missing_values = np.nan , strategy = 'mean')  # where ever nan replace with mean of that col
# this also for alias

# SHIFT + TAB FOR OFFLINE SUGGESTIONS

si2 = SimpleImputer(missing_values = np.nan , strategy = 'median')

si3 = SimpleImputer(missing_values = np.nan , strategy = 'most_frequent') # for mode 

si3.fit(table) 
temp = si3.transform(table)

# or

# si.fit_transform(table)


# now convert to dataframe
df1 = pd.DataFrame(temp,columns = ['one','two'])

df1

   one  two
0  1.0  1.0
1  2.0  2.0
2  1.0  3.0
3  1.0  4.0
4  5.0  1.0

In [12]:
# using fillna no needed sklearn here

x = table.fillna(20)
x

    one   two
a   1.0   1.0
b   2.0   2.0
c  20.0   3.0
d  20.0   4.0
e   5.0  20.0

# 2.HANDLING CATEGORICAL DATA

## 2.1 Using get_dummies() (from pandas library)

In [15]:
# categorical has textual data also we need to convert to numeric form

# can be nominal and ordinal 

''' nominal -> onehotencoder
           ->  get_dummies 
           
    oridnal -> labelencoder

    number of categories == number of columns created
'''

   one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN

In [19]:
data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

print(type(data))

data = pd.DataFrame(data)

data

<class 'dict'>

   customer_id       loan_type Income
0            1       Home loan    15k
1            2   Personal loan    20k
2            3  Education loan    30k
3            4        Car loan    40k
4            5       Home loan    50k

In [26]:
pd.get_dummies(data['loan_type'])
loan_info = pd.get_dummies(data['loan_type'],dtype=int)

print(loan_info)

print()

income_info = pd.get_dummies(data['Income'],dtype=int)

print(income_info)

   Car loan  Education loan  Home loan  Personal loan
0         0               0          1              0
1         0               0          0              1
2         0               1          0              0
3         1               0          0              0
4         0               0          1              0

   15k  20k  30k  40k  50k
0    1    0    0    0    0
1    0    1    0    0    0
2    0    0    1    0    0
3    0    0    0    1    0
4    0    0    0    0    1

In [39]:
whole_data = pd.get_dummies(data,dtype = int,prefix_sep = ' : ')
whole_data

,customer_id,loan_type : Car loan,loan_type : Education loan,loan_type : Home loan,loan_type : Personal loan,Income : 15k,Income : 20k,Income : 30k,Income : 40k,Income : 50k
0,1,0,0,1,0,1,0,0,0,0
1,2,0,0,0,1,0,1,0,0,0
2,3,0,1,0,0,0,0,1,0,0
3,4,1,0,0,0,0,0,0,1,0
4,5,0,0,1,0,0,0,0,0,1

### 2.2 using OneHotEncoder() (from sklearn library)

In [44]:
from sklearn.preprocessing import OneHotEncoder

data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

data = pd.DataFrame(data)

one = OneHotEncoder()

one

OneHotEncoder()

In [48]:
x = one.fit_transform(data)
x1 = one.fit_transform(data).toarray()
print(x)
print()
print(x1)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (5, 14)>
  Coords	Values
  (0, 0)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (1, 1)	1.0
  (1, 8)	1.0
  (1, 10)	1.0
  (2, 2)	1.0
  (2, 6)	1.0
  (2, 11)	1.0
  (3, 3)	1.0
  (3, 5)	1.0
  (3, 12)	1.0
  (4, 4)	1.0
  (4, 7)	1.0
  (4, 13)	1.0

[[1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]]

In [53]:
from sklearn.preprocessing import LabelEncoder

data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

data = pd.DataFrame(data)

le = LabelEncoder()
le

LabelEncoder()

In [56]:
# x = le.fit_transform(data)
# above gives error

x = data.apply(le.fit_transform)
x

   customer_id  loan_type  Income
0            0          2       0
1            1          3       1
2            2          1       2
3            3          0       3
4            4          2       4

# 3. Scaling of Data

### 3.1 MinMax Scaler
### 3.2 Standard Scaler
### 3.3 Robust Scaler

In [ ]:
'''
SCALING IS TO MAKE TO RANGE OF DATA BETWEEN A CERTAIN RANGE OF WHOLE DATASET

3.1 minmax 
x = (x - xmin) / (xmax - xmin)

3.2 Standard scaler
x = (x - μ) /  σ 

3.3 Robust Scaler
x = (x - median) / IQR

'''

In [64]:
data = np.array([[-100.3],[27.5],[0],[-200],[1000]])



print('before scaling \n',data,'\n')

before scaling
 [[-100.3]
 [  27.5]
 [   0. ]
 [-200. ]
 [1000. ]]

In [70]:
from sklearn import preprocessing

mm = preprocessing.MinMaxScaler()
mm1 = preprocessing.MinMaxScaler(feature_range=(5,10))
mm2 = preprocessing.MinMaxScaler(feature_range=(100,200))

In [71]:
scaled = mm2.fit_transform(data)

scaled

array([[108.30833333],
       [118.95833333],
       [116.66666667],
       [100.        ],
       [200.        ]])

In [72]:
ss = preprocessing.StandardScaler()

StandardScaler()

In [73]:
x = ss.fit_transform(data)
x
# -3 to 3 range here

array([[-0.56524004],
       [-0.27128026],
       [-0.33453451],
       [-0.79456547],
       [ 1.96562028]])

In [76]:
rs = preprocessing.RobustScaler()

x = rs.fit_transform(data)
x

array([[-0.78482003],
       [ 0.21517997],
       [ 0.        ],
       [-1.56494523],
       [ 7.82472613]])