## Data Handling Using Pandas

### Creation of Series

#### (A)Creation of Series from Scalar Values

In [1]:
# series and dataframe in pandas
# default 0 index series
# series (lst,index) 
# hetergenous index allowed in series

In [2]:
import pandas as pd
import numpy as np

In [3]:
series1 = pd.Series([10,20,30])
print(series1)
print(type(series1))

0    10
1    20
2    30
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
series2 = pd.Series(["Kavi","Shyam","Ravi"], index=[3,'test',1])
print(series2)

3        Kavi
test    Shyam
1        Ravi
dtype: object

#### (B)Creation of Series from NumPy Arrays

In [5]:
array1 = np.array([1,2,3,4])
lst = [12,23,25,26]
series3 = pd.Series(array1)
series4 = pd.Series(lst)
print(series3)
print(series4)

0    1
1    2
2    3
3    4
dtype: int32
0    12
1    23
2    25
3    26
dtype: int64

In [6]:
series4 = pd.Series(array1, index = ["Jan","Feb", "Mar", "Apr"])
print(series4)

Jan    1
Feb    2
Mar    3
Apr    4
dtype: int32

In [7]:
#series5 = pd.Series(array1, index = ["Jan","Feb", "Mar"])

#### (C)Creation of Series from Dictionary

In [8]:
dict1 = {'India': 'NewDelhi', 'UK':'London', 'Japan': 'Tokyo'}
print(dict1)

{'India': 'NewDelhi', 'UK': 'London', 'Japan': 'Tokyo'}

In [9]:
series8 = pd.Series(dict1)
print(series8)

India    NewDelhi
UK         London
Japan       Tokyo
dtype: object

### Accessing Elements of a Series

#### (A)Indexing

In [10]:
seriesNum = pd.Series([10,20,30,40,50,60])
seriesNum[4]

50

In [11]:
seriesMnths = pd.Series([2,3,4,5],index=["Feb","Mar","Apr","Mar"])
seriesMnths["Mar"]

Mar    3
Mar    5
dtype: int64

In [12]:
seriesCapCntry = pd.Series(['NewDelhi','WashingtonDC', 'London', 'Paris'],
index=['India', 'USA', 'UK', 'France'])

In [13]:
seriesCapCntry['India']
seriesCapCntry[1:3]  # no error
# seriesCapCntry[2]  error

USA    WashingtonDC
UK           London
dtype: object

In [14]:
seriesCapCntry[1]

C:\Users\TEMP.SYSTEMA40.020\AppData\Local\Temp\ipykernel_9252\3676189266.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seriesCapCntry[1]

'WashingtonDC'

In [15]:
seriesCapCntry[[3,2]]

C:\Users\TEMP.SYSTEMA40.020\AppData\Local\Temp\ipykernel_9252\1704503957.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seriesCapCntry[[3,2]]

France     Paris
UK        London
dtype: object

In [16]:
seriesCapCntry[['UK','USA']]

UK           London
USA    WashingtonDC
dtype: object

In [17]:
seriesCapCntry.index=[10,20,30,40]
seriesCapCntry

10        NewDelhi
20    WashingtonDC
30          London
40           Paris
dtype: object

#### (B)Slicing

In [18]:
seriesCapCntry = pd.Series(['NewDelhi', 'WashingtonDC', 'London','Paris'], index=['India', 'USA', 'UK', 'France'])

In [19]:
seriesCapCntry[1:3]

USA    WashingtonDC
UK           London
dtype: object

In [20]:
seriesCapCntry['USA' : 'France']

USA       WashingtonDC
UK              London
France           Paris
dtype: object

In [21]:
seriesCapCntry[ : : -1]

France           Paris
UK              London
USA       WashingtonDC
India         NewDelhi
dtype: object

In [22]:
import numpy as np
seriesAlph = pd.Series(np.arange(10,16,1),
index = ['a', 'b', 'c', 'd', 'e', 'f'])

In [23]:
seriesAlph

a    10
b    11
c    12
d    13
e    14
f    15
dtype: int32

In [24]:
seriesAlph[1:3] = 50 # series 1st and 2nd elemnt become 50
seriesAlph

a    10
b    50
c    50
d    13
e    14
f    15
dtype: int32

In [25]:
seriesAlph['c':'e'] = 500
seriesAlph

a     10
b     50
c    500
d    500
e    500
f     15
dtype: int32

### Attributes of Series

In [26]:
seriesCapCntry

India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
dtype: object

In [27]:
seriesCapCntry.name = 'Capitals'  #whole series ka name
print(seriesCapCntry)

India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
Name: Capitals, dtype: object

In [28]:
seriesCapCntry.index.name ='Countries' #indices ka name
print(seriesCapCntry)

Countries
India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
Name: Capitals, dtype: object

In [29]:
print(seriesCapCntry.values) # values of series only

['NewDelhi' 'WashingtonDC' 'London' 'Paris']

In [30]:
print(seriesCapCntry.size) # includes None / values too

4

In [31]:
seriesCapCntry.empty

False

In [32]:
seriesEmpt=pd.Series()
seriesEmpt.empty

True

### Methods of Series

In [33]:
seriesTenTwenty=pd.Series(np.arange( 10,20, 1 ))
print(seriesTenTwenty)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [34]:
seriesTenTwenty.head(2)  #frist 2 entries

0    10
1    11
dtype: int32

In [35]:
seriesTenTwenty.head()  # by default first 5 entries

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [36]:
seriesTenTwenty.count() # counts the number of enteries excludes None values

10

In [37]:
seriesTenTwenty.tail(2) # last 2

8    18
9    19
dtype: int32

In [38]:
seriesTenTwenty.tail() # by deauflt last 5

5    15
6    16
7    17
8    18
9    19
dtype: int32

### Mathematical Operations on Series

In [39]:
seriesA = pd.Series([1,2,3,4,5], index =['a', 'b', 'c', 'd', 'e'])

In [40]:
seriesA

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [41]:
seriesB = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])

In [42]:
seriesB

z     10
y     20
a    -10
c    -50
e    100
dtype: int64

#### (A)Addition of two Series

In [43]:
seriesA + seriesB

a     -9.0
b      NaN
c    -47.0
d      NaN
e    105.0
y      NaN
z      NaN
dtype: float64

In [44]:
seriesA.add(seriesB, fill_value=0.0)

a     -9.0
b      2.0
c    -47.0
d      4.0
e    105.0
y     20.0
z     10.0
dtype: float64

#### (B)Subtraction of two Series

In [45]:
seriesA - seriesB

a    11.0
b     NaN
c    53.0
d     NaN
e   -95.0
y     NaN
z     NaN
dtype: float64

In [46]:
seriesA.sub(seriesB, fill_value=1000)

a     11.0
b   -998.0
c     53.0
d   -996.0
e    -95.0
y    980.0
z    990.0
dtype: float64

#### (C)Multiplication of two Series

In [47]:
seriesA * seriesB

a    -10.0
b      NaN
c   -150.0
d      NaN
e    500.0
y      NaN
z      NaN
dtype: float64

In [48]:
seriesA.mul(seriesB, fill_value=0)

a    -10.0
b      0.0
c   -150.0
d      0.0
e    500.0
y      0.0
z      0.0
dtype: float64

#### (D)Division of two Series

In [49]:
seriesA/seriesB

a   -0.10
b     NaN
c   -0.06
d     NaN
e    0.05
y     NaN
z     NaN
dtype: float64

##

## DataFrame
<!-- imp for ML -->

### Creation of DataFrame

#### (A)Creation of an empty DataFrame

In [50]:
# comes with row index and column as well
# similar to SQL table 
# excel <-> csv <-> dataframe
# by default 0 index

In [51]:
import pandas as pd
dFrameEmt = pd.DataFrame()
dFrameEmt

Empty DataFrame
Columns: []
Index: []

#### (B)Creation of DataFrame from NumPy ndarrays

In [52]:
import numpy as np
array1 = np.array([10,20,30])
array2 = np.array([100,200,300])
array3 = np.array([-10,-20,-30, -40])
dFrame4 = pd.DataFrame(array1)
dFrame4

    0
0  10
1  20
2  30

In [53]:
dFrame5 = pd.DataFrame([array1, array3,array2], columns=[ 'A', 'B', 'C', 'D'])
dFrame5


dFrame5 = pd.DataFrame([array1, array3,array2])
dFrame5

     0    1    2     3
0   10   20   30   NaN
1  -10  -20  -30 -40.0
2  100  200  300   NaN

#### (C)Creation of DataFrame from List of Dictionaries

In [54]:
listDict = [{'a':10, 'b':20}, {'a':5, 'b':10, 'c':20},{'e' : 25}]

In [55]:
dFrameListDict = pd.DataFrame(listDict)
print(dFrameListDict)

dFrameListDict

      a     b     c     e
0  10.0  20.0   NaN   NaN
1   5.0  10.0  20.0   NaN
2   NaN   NaN   NaN  25.0

      a     b     c     e
0  10.0  20.0   NaN   NaN
1   5.0  10.0  20.0   NaN
2   NaN   NaN   NaN  25.0

#### (D)Creation of DataFrame from Dictionary of Lists

In [56]:
dictForest = {'State': ['Assam', 'Delhi',
'Kerala'],
'GArea': [78438, 1483, 38852] ,
'VDF' : [2797, 6.72,1663]}
dFrameForest= pd.DataFrame(dictForest)
dFrameForest

    State  GArea      VDF
0   Assam  78438  2797.00
1   Delhi   1483     6.72
2  Kerala  38852  1663.00

In [57]:
dFrameForest1 = pd.DataFrame(dictForest,
columns = ['State','VDF', 'GArea'])
dFrameForest1

    State      VDF  GArea
0   Assam  2797.00  78438
1   Delhi     6.72   1483
2  Kerala  1663.00  38852

#### (E)Creation of DataFrame from Series

In [58]:
dFrame6 = pd.DataFrame(seriesA)
dFrame6

dFramet = pd.DataFrame(seriesB)
dFramet

     0
z   10
y   20
a  -10
c  -50
e  100

In [59]:
dFrame7 = pd.DataFrame([seriesA, seriesB])
dFrame7

      a    b     c    d      e     z     y
0   1.0  2.0   3.0  4.0    5.0   NaN   NaN
1 -10.0  NaN -50.0  NaN  100.0  10.0  20.0

In [60]:
seriesC = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])

In [61]:
dFrame8 = pd.DataFrame([seriesA, seriesC])
dFrame8

      a    b     c    d      e     z     y
0   1.0  2.0   3.0  4.0    5.0   NaN   NaN
1 -10.0  NaN -50.0  NaN  100.0  10.0  20.0

#### (F)Creation of DataFrame from Dictionary of Series

In [62]:
ResultSheet={
'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Samridhi': pd.Series([89, 91, 88],index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67],index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99,45],index=['Maths','Science','Hindi','OMG'])}

In [63]:
ResultDF = pd.DataFrame(ResultSheet)
ResultDF

         Arnab  Ramit  Samridhi  Riya  Mallika
Hindi     97.0   96.0      88.0  67.0       99
Maths     90.0   92.0      89.0  81.0       94
OMG        NaN    NaN       NaN   NaN       45
Science   91.0   81.0      91.0  71.0       95

In [64]:
type(ResultDF.Arnab)

# ResultDF.Arnab

pandas.core.series.Series

In [65]:
dictForUnion = { 'Series1' : pd.Series([1,2,3,4,5],index = ['a', 'b', 'c', 'd', 'e']) ,
'Series2' :pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e']),
'Series3' :pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e']) }

In [66]:
dFrameUnion = pd.DataFrame(dictForUnion)
dFrameUnion

   Series1  Series2  Series3
a      1.0    -10.0    -10.0
b      2.0      NaN      NaN
c      3.0    -50.0    -50.0
d      4.0      NaN      NaN
e      5.0    100.0    100.0
y      NaN     20.0     20.0
z      NaN     10.0     10.0

### Operations on rows and columns in DataFrames

#### (A)Adding a New Column to a DataFrame

In [67]:
ResultDF['Preeti']=[89,78,76]
ResultDF

ValueError: Length of values (3) does not match length of index (4)

In [ ]:
ResultDF['Ramit']=[99, 98, 78]
ResultDF

In [ ]:
ResultDF['Arnab']=91  # ALL values of arnab becomes 91
ResultDF

#### (B) Adding a New Row to a DataFrame

In [ ]:
ResultDF

In [ ]:
ResultDF.loc['English'] = [85, 86, 83, 80, 90, 89]
ResultDF

In [ ]:
ResultDF.loc['English'] = [95, 86, 95, 80, 95,99]
ResultDF

In [ ]:
ResultDF.loc['Maths']=0
ResultDF

In [ ]:
ResultDF[: ] = 0 # Set all values in ResultDF to 0
ResultDF

#### (C)Deleting Rows or Columns from a DataFrame

In [ ]:
ResultDF

In [ ]:
ResultDF = ResultDF.drop('Science', axis=0)
ResultDF

In [ ]:
ResultDF = ResultDF.drop(['Samridhi','Ramit','Riya'], axis=1)
ResultDF

In [ ]:
ResultDF

In [ ]:
ResultDF= ResultDF.drop('Hindi', axis=0)
ResultDF

#### (D)Renaming Row Labels of a DataFrame

In [ ]:
ResultDF

In [ ]:
ResultDF=ResultDF.rename({'Maths':'Sub1','Science':'Sub2','English':'Sub3','Hindi':'Sub4'}, axis='index')
print(ResultDF)

In [ ]:
ResultDF=ResultDF.rename({'Maths':'Sub1','Science':'Sub2','Hindi':'Sub4'}, axis='index')
print(ResultDF)

#### (E)Renaming Column Labels of a DataFrame

In [ ]:
ResultDF=ResultDF.rename({'Arnab':'Student1','Ramit':'Student2','Samridhi':'Student3','Mallika':'Student4'},axis='columns')
print(ResultDF)

### Accessing DataFrames Element through Indexing

#### (A)Label Based Indexing

In [ ]:
ResultDF

In [ ]:
dFrame10Multiples = pd.DataFrame([10,20,30,40,50])

In [ ]:
dFrame10Multiples.loc[2]

In [ ]:
ResultDF.loc[:,'Arnab']

In [ ]:
print(df['Arnab'])

In [ ]:
ResultDF.loc[['Science', 'Hindi']]

#### (B)Boolean Indexing

In [ ]:
ResultDF.loc['Maths'] > 90

In [ ]:
ResultDF.loc[:,'Arnab']>90

### Accessing DataFrames Element through Slicing

In [ ]:
ResultDF.loc['Maths': 'Science']

In [ ]:
ResultDF.loc['Maths': 'Science', 'Arnab']

In [ ]:
ResultDF.loc['Maths': 'Science', 'Arnab':'Samridhi']

In [ ]:
ResultDF.loc['Maths': 'Science',['Arnab','Samridhi']]

#### Filtering Rows in DataFrames

In [ ]:
ResultDF.loc[[True, False, True]]

### Joining, Merging and Concatenation of DataFrames

#### (A)Joining

In [ ]:
dFrame1=pd.DataFrame([[1, 2, 3], [4, 5],[6]], columns=['C1', 'C2', 'C3'], index=['R1','R2', 'R3'])
dFrame1

In [ ]:
dFrame2=pd.DataFrame([[10, 20], [30], [40,50]], columns=['C2', 'C5'], index=['R4', 'R2','R5'])
dFrame2

In [ ]:
dFrame1=dFrame1.append(dFrame2)
dFrame1

In [ ]:
dFrame2 =dFrame2.append(dFrame1,sort='True')
dFrame2

In [ ]:
dFrame2 = dFrame2.append(dFrame1,sort=’False’)
dFrame2