In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# always by deafult data profiling in exam

In [3]:
data = pd.read_csv('hotel_bookings.csv')

In [4]:
data.describe()
data.describe().T

print(data)

               hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015
1       Resort Hotel            0        737               2015
2       Resort Hotel            0          7               2015
3       Resort Hotel            0         13               2015
4       Resort Hotel            0         14               2015
...              ...          ...        ...                ...
119385    City Hotel            0         23               2017
119386    City Hotel            0        102               2017
119387    City Hotel            0         34               2017
119388    City Hotel            0        109               2017
119389    City Hotel            0        205               2017

       arrival_date_month  arrival_date_week_number  \
0                    July                        27
1                    July                        27
2                    July                        27
3                    July                        27
4                    July                        27
...                   ...                       ...
119385             August                        35
119386             August                        35
119387             August                        35
119388             August                        35
119389             August                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0
1                               1                        0
2                               1                        0
3                               1                        0
4                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN
1                          0       2  ...    No Deposit    NaN     NaN
2                          1       1  ...    No Deposit    NaN     NaN
3                          1       1  ...    No Deposit  304.0     NaN
4                          2       2  ...    No Deposit  240.0     NaN
...                      ...     ...  ...           ...    ...     ...
119385                     5       2  ...    No Deposit  394.0     NaN
119386                     5       3  ...    No Deposit    9.0     NaN
119387                     5       2  ...    No Deposit    9.0     NaN
119388                     5       2  ...    No Deposit   89.0     NaN
119389                     7       2  ...    No Deposit    9.0     NaN

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00
1                         0     Transient    0.00
2                         0     Transient   75.00
3                         0     Transient   75.00
4                         0     Transient   98.00
...                     ...           ...     ...
119385                    0     Transient   96.14
119386                    0     Transient  225.43
119387                    0     Transient  157.71
119388                    0     Transient  104.40
119389                    0     Transient  151.20

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0
1                                 0                          0
2                                 0                          0
3                                 0                          0
4                                 0                          1
...                             ...                        ...
119385                            0                          0
119386                            0                          2
119387                            0                          4
119388                            0                          0
119389                            0                          2

        reservation_status reservation_status_date
0                Check-Out              2015-07-01
1                Check-Out              2015-07-01
2                Check-Out              2015-07-02
3                Check-Out              2015-07-02
4                Check-Out              2015-07-03
...                    ...                     ...
119385           Check-Out              2017-09-06
119386           Check-Out              2017-09-07
119387           Check-Out              2017-09-07
119388           Check-Out              2017-09-07
119389           Check-Out              2017-09-07

[119390 rows x 32 columns]

In [5]:
data.tail()
data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [7]:
data.shape

(119390, 32)

In [8]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Length: 119390, dtype: bool

In [9]:
data.duplicated().sum()

np.int64(31994)

In [10]:
data.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [11]:
data.shape
data = data.drop(['company'],axis=1)
# we drop company as there are huge percentage of nulls 

data.isna().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             488
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16340
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [12]:
mode_country = data['country'].mode()[0]

print(mode_country)

PRT

In [13]:
data['country'] = data['country'].fillna(mode_country)

data['country']

0         PRT
1         PRT
2         GBR
3         GBR
4         GBR
         ...
119385    BEL
119386    FRA
119387    DEU
119388    GBR
119389    DEU
Name: country, Length: 119390, dtype: str

In [ ]:
# Q3

'''
NOTE rules of thumb 
Just remember these patterns:
- data.loc[row_label, column_label]
- data.iloc[row_position, column_position]
- data.index[i] gives you the index label of the row at position i.
'''

data = pd.read_csv('hotel_bookings.csv')

set(data['hotel']) # its categotgorical 
# if city hotel then 0 else 0

for i in range(0,len(data['hotel'])):
    if(data.loc[i,'hotel'] == 'City Hotel'):
        data.loc[i,'hotel'] = '1'
    else:
        data.loc[i,'hotel'] = '0'

print(data.sample(10)['hotel'])

In [15]:
data['hotel'][len(data)-1]

'1'

In [16]:
data['hotel'] = np.where(data['hotel'].str.contains('City Hotel'),1,0)

print(data['hotel'])

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: hotel, Length: 119390, dtype: int64

In [17]:
# LABEL ENCODER

from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

data['country_code'] = LE.fit_transform(data['country'])

data.sample(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,country_code
12097,0,1,133,2017,June,24,13,0,4,2,...,410.0,NaN,0,Transient,56.70,0,0,Canceled,2017-01-31,135
16816,0,0,113,2015,September,37,10,1,3,2,...,241.0,NaN,0,Transient,94.37,0,2,Check-Out,2015-09-14,135
105915,0,0,56,2017,February,7,12,2,4,2,...,9.0,NaN,0,Transient,90.10,0,2,Check-Out,2017-02-18,56
52644,0,1,43,2016,June,24,9,0,1,2,...,7.0,NaN,0,Transient,75.54,0,1,Canceled,2016-05-14,135
59790,0,1,70,2016,November,45,1,0,4,3,...,9.0,NaN,0,Transient,126.00,0,1,Canceled,2016-10-24,15

In [18]:
data['arrival_date_month']

0           July
1           July
2           July
3           July
4           July
           ...
119385    August
119386    August
119387    August
119388    August
119389    August
Name: arrival_date_month, Length: 119390, dtype: str

In [19]:
# USING get_dummies()

data1 = pd.get_dummies(data,columns=['arrival_date_month'],prefix = 'month',drop_first=False)


print(data1)

        hotel  is_canceled  lead_time  arrival_date_year  \
0           0            0        342               2015
1           0            0        737               2015
2           0            0          7               2015
3           0            0         13               2015
4           0            0         14               2015
...       ...          ...        ...                ...
119385      0            0         23               2017
119386      0            0        102               2017
119387      0            0         34               2017
119388      0            0        109               2017
119389      0            0        205               2017

        arrival_date_week_number  arrival_date_day_of_month  \
0                             27                          1
1                             27                          1
2                             27                          1
3                             27                          1
4                             27                          1
...                          ...                        ...
119385                        35                         30
119386                        35                         31
119387                        35                         31
119388                        35                         31
119389                        35                         29

        stays_in_weekend_nights  stays_in_week_nights  adults  children  ...  \
0                             0                     0       2       0.0  ...
1                             0                     0       2       0.0  ...
2                             0                     1       1       0.0  ...
3                             0                     1       1       0.0  ...
4                             0                     2       2       0.0  ...
...                         ...                   ...     ...       ...  ...
119385                        2                     5       2       0.0  ...
119386                        2                     5       3       0.0  ...
119387                        2                     5       2       0.0  ...
119388                        2                     5       2       0.0  ...
119389                        2                     7       2       0.0  ...

        month_December month_February month_January month_July month_June  \
0                False          False         False       True      False
1                False          False         False       True      False
2                False          False         False       True      False
3                False          False         False       True      False
4                False          False         False       True      False
...                ...            ...           ...        ...        ...
119385           False          False         False      False      False
119386           False          False         False      False      False
119387           False          False         False      False      False
119388           False          False         False      False      False
119389           False          False         False      False      False

        month_March  month_May  month_November month_October month_September
0             False      False           False         False           False
1             False      False           False         False           False
2             False      False           False         False           False
3             False      False           False         False           False
4             False      False           False         False           False
...             ...        ...             ...           ...             ...
119385        False      False           False         False           False
119386        False      False           False         False           False
119387        False      False           False         False           False
119388        False      False           False         False           False
119389        False      False           False         False           False

[119390 rows x 44 columns]

In [20]:
# HW
# standard scalar, robust scaler, minmax scaler 
# on lead_time