In [8]:
import numpy as np
import pandas as pd

In [9]:
# label based indexing

# iloc loc

# [i1,i3,..] indexing
# [i1 : i4]  sliciing

# DA then stats using strach
# AP can use this functions

In [10]:
print("hello")

hello

In [14]:
df1 = pd.DataFrame([[1,2,3],[4,5],[6]],index = ['i1','i2','i3'],columns=['c1','c2','c3'])
df1

    c1   c2   c3
i1   1  2.0  3.0
i2   4  5.0  NaN
i3   6  NaN  NaN

In [15]:
df2 = pd.DataFrame([[10,20,30],[40,50],[60,89]],index = ['i1','i2','i3'],columns=['c1','c2','c3'])
df2

    c1  c2    c3
i1  10  20  30.0
i2  40  50   NaN
i3  60  89   NaN

In [24]:
print(df1.index)
print(df1.dtypes)
print(df1.columns)
print(df1.shape)
print(df1.size)
print(df1.T)
print(df1.head(2))
print(df1.tail(2))

c1      int64
c2    float64
c3    float64
dtype: object
Index(['c1', 'c2', 'c3'], dtype='str')
(3, 3)
9
     i1   i2   i3
c1  1.0  4.0  6.0
c2  2.0  5.0  NaN
c3  3.0  NaN  NaN
    c1   c2   c3
i1   1  2.0  3.0
i2   4  5.0  NaN
i3   6  NaN  NaN

In [36]:
# import csv <-> df
xyz = pd.read_csv("Book1.csv",sep=',',header=None)

print(xyz)
# xyz needed to convert to df now

print(type(xyz))

       0    1
0     12  asd
1    123  asd
2    124  asd
3     23  asd
4  42345  asd
5    234  asd
<class 'pandas.DataFrame'>

In [41]:
print(df1.mean())
print(df1.describe())
print(df1.max())
print(df1.sum())
print(df1['c1'].sum())

c1    3.666667
c2    3.500000
c3    3.000000
dtype: float64
             c1       c2   c3
count  3.000000  2.00000  1.0
mean   3.666667  3.50000  3.0
std    2.516611  2.12132  NaN
min    1.000000  2.00000  3.0
25%    2.500000  2.75000  3.0
50%    4.000000  3.50000  3.0
75%    5.000000  4.25000  3.0
max    6.000000  5.00000  3.0
c1    6.0
c2    5.0
c3    3.0
dtype: float64
c1    11.0
c2     7.0
c3     3.0
dtype: float64
11

In [42]:
print(df1.median())

c1    4.0
c2    3.5
c3    3.0
dtype: float64

In [43]:
df1.quantile()

c1    4.0
c2    3.5
c3    3.0
Name: 0.5, dtype: float64