<img src="Pandas.png" width = 500>

## <font color="green"><h3>What is Pandas?</h3></font>
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

## <font color="green"><h3>Key features of Pandas:</h3></font>

**Some key features of Pandas are as follows:-**

1. It provides tools for reading and writing data from a wide variety of sources such as CSV files, excel files, databases such as SQL, JSON files.


2. It provides different data structures like series, dataframe and panel for data manipulation and indexing.


3. It can handle wide variety of data sets in different formats – time series, heterogeneous data, tabular and matrix data.


4. It can perform variety of operations on datasets. It includes subsetting, slicing, filtering, merging, joining, groupby, reordering.


5. It can deal with missing data by either deleting them or filling them with zeros or a suitable test statistic.


6. It integrates well with other Python libraries such as Scikit-learn, statsmodels and SciPy.

## <font color="green"><h3>Pandas DataFrame:</h3></font>
    
• A Dataframe is a two-dimensional data structure. So, data is aligned in a tabular format in rows and columns.

• It is similar to structured arrays in NumPy with mutability added.

• Properties of Dataframe are as follows:-

• The dataframe is conceptually analogous to a table or spreadsheet of data.

• Its columns are of different types – float64, int, bool, and so on.

• A Dataframe column is a Series structure.

• Its size is mutable – columns can be inserted and deleted.

• It has labelled axes (rows and columns).

## <font color="green"><h3>Advantages of Pandas:</h3></font>

Pandas is a core component of the Python data analysis toolkit. Pandas provides data structure and operations facilities, which is particularly useful for data analysis. There are various advantages of using Pandas for data analysis.

These advantages are as follows:-
#### Data representation

It represents data in a form that is very much suited for data analysis through its Dataframe and Series data structures.

#### Data subsetting and filtering

It provides for easy subsetting and filtering of data. It provides procedures that are suited for data analysis.

#### Concise and clear code

It provides functionality to write clear and concise code. It allows us to focus on the task at hand, rather than have to write tedious code.

<font color="green"><h2>Data structures in Pandas</h2></font>

Pandas provide easy to use data structures.

There are three main data structures in Pandas. 

They are:-
    
    Series
    Dataframe
    
These data structures are built on top of Numpy array, which means they are fast.

### Installation of Pandas
    !pip install pandas

### <font color="green"><h3>Import Pandas</h3></font>

In [1]:
import pandas as pd

<font color="green"><h2>Pandas Series</h2></font>

A Pandas Series is a one-dimensional array like structure with homogeneous data.

The data can be of any type (integer, string, float, etc.). The axis labels are collectively called index.

For example, the following series is a collection of integers 10, 20, 30, 40, 50, 60, 70, 80, 90, 100.

**Creating a series from Lists**

In [2]:
# simple array
import numpy as np
data=np.array(['a','b','c','d','e'])
# providing an index
ser=pd.Series(data,index=[10,11,12,13,14])
print(ser)

10    a
11    b
12    c
13    d
14    e
dtype: object

**Creating a series from Dictionary**

In [3]:
# a simple dictionary {key:value}
dict = { 'ABC':10,'DEF':20,'GHI':30}
# create series from dictionary
ser=pd.Series(dict)
print(ser)

ABC    10
DEF    20
GHI    30
dtype: int64

<font color="green"><h2>Pandas DataFrame</h2></font>

A Dataframe is a two-dimensional data structure. So, data is aligned in a tabular fashion in rows and columns. 

Its column types can beheterogeneous: - that is, of varying types. It is similar to structured arrays in NumPy with mutability added.

## <font color="green"><h4>Different ways to create dataframe in pandas
## <font color="green">1) Using csv</h3></font>

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("abc.csv")
data

Empty DataFrame
Columns: [nd]
Index: []

In [ ]:
data=pd.to_csv("")
data

In [4]:
#reading the csv file
df_1=pd.read_csv("")
df_1

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

**to_string() : this is for printing whole dataset**

In [5]:
#print(df.to_string())

## <font color="green">2) Using excel</h3></font>

In [6]:
#reading the excel file
df_2=pd.read_excel("data.xlsx")
df_2

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### Note : If you get an error while reading excel (.xlsx) file then run the below code

    !pip install openpyxl

## <font color="green">3) Using dictionary</h3></font>

In [7]:
#create a dictionary
weather_data = {
    "day" : ['1/1/2022','1/2/2022','1/3/2022'],
    "temperature" : [32,35,28],
    "windspeed" : [6,7,2],
    "event" : ['rain','sunny', 'snow']
}
#converting dictionary into dataframe
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2022           32          6   rain
1  1/2/2022           35          7  sunny
2  1/3/2022           28          2   snow

## <font color="green">4) Using tuples list</h3></font>

In [8]:
#Create a list of tuples
weather_data = [
    ('1/1/2022',32,6,'rain'),
    ('1/2/2022',35,7,'sunny'),
    ('1/3/2022',28,2,'snow')
]
df = pd.DataFrame(weather_data, columns=['Day',"Temperature","Windspeed","Event"])
df

        Day  Temperature  Windspeed  Event
0  1/1/2022           32          6   rain
1  1/2/2022           35          7  sunny
2  1/3/2022           28          2   snow

## <font color="green">5) Using list of dictionaries</h3></font>

In [9]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},    
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## <font color="green"><h4>Read/Write CSV and Excel Files in Pandas

### <font color="green">Read CSV

In [10]:
df = pd.read_csv("stock_data.csv")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [11]:
df = pd.read_csv("stock_data.csv", skiprows=1)
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [12]:
# skiprows and header are kind of same
df = pd.read_csv("stock_data.csv", header=1) 
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [13]:
df = pd.read_csv("stock_data.csv", header=None, names = ["ticker","eps","revenue","people"])
df

                ticker      eps revenue         people
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata

In [14]:
df = pd.read_csv("stock_data.csv",  nrows=2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

### <font color="green">Write to CSV</color>

In [15]:
df.to_csv("new.csv", index=False)

In [16]:
df.to_csv("new.csv",header=False)

In [17]:
df.to_csv("new.csv", columns=["tickers","price"], index=False)

### <font color="green">Read Excel</color>

In [18]:
df = pd.read_excel("stock_data.xlsx","Sheet1")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

### <font color="green">Write to Excel</color>

In [19]:
df.to_excel("new.xlsx", sheet_name="stocks", index=False)

**Write two dataframes to two separate sheets in excel**

In [20]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [21]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")

## <font color="green"><h4>JSON</font>

What is a JSON File?

JavaScript Object Notation (JSON) is a data format that stores data in a human-readable form. While it can be technically be used for storage, JSON files are primarily used for serialization and information exchange between a client and server.

Although it was derived from JavaScript, it's platform-agnostic and is a widely-spread and used format - most prevalently in REST APIs.

Import json Module

To work with JSON (string, or file containing JSON object), you can use Python's json module.

In [22]:
import json

**Python dict to JSON**

You can parse a JSON string using json.loads() method. The method returns a dictionary.

In [23]:
person = '{"name": "Bob", "languages": ["English", "French"]}'
person_dict = json.loads(person)

print( person_dict)

print(person_dict['languages'])

{'name': 'Bob', 'languages': ['English', 'French']}
['English', 'French']

Here, person is a JSON string, and person_dict is a dictionary.

## <font color="green"><h4>Some important function in dataframe</font>

In [24]:
df = pd.read_csv("weather_data.csv",parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

<font color="green"><h4>check the type of dataframe</font>

In [25]:
type(df)

pandas.core.frame.DataFrame

<font color="green"><h4>check shape of dataframe

In [26]:
df.shape

(9, 4)

In [27]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [28]:
df.set_index('day',inplace=True) #inplace=True, means it will make changes in the main dataframe
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [29]:
#head() used for printing top rows of the dataframe
df[['temperature', 'windspeed']].head()

            temperature  windspeed
day
2017-01-01         32.0        6.0
2017-01-04          NaN        9.0
2017-01-05         28.0        NaN
2017-01-06          NaN        7.0
2017-01-07         32.0        NaN

<font color="green"><h4>view concise summary of datafram

We can view the concise summary of dataframe with info() method :

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9 entries, 2017-01-01 to 2017-01-11
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  5 non-null      float64
 1   windspeed    5 non-null      float64
 2   event        7 non-null      object
dtypes: float64(2), object(1)
memory usage: 288.0+ bytes

In [31]:
df.describe()

       temperature  windspeed
count      5.00000   5.000000
mean      33.20000   8.400000
std        4.38178   2.302173
min       28.00000   6.000000
25%       32.00000   7.000000
50%       32.00000   8.000000
75%       34.00000   9.000000
max       40.00000  12.000000

 <font color="green"><h4>Check missing values with pandas

In [32]:
df.isnull().sum()

temperature    4
windspeed      4
event          2
dtype: int64

**isna() and notna() functions to detect 'NA' values**

Pandas provides isna() and notna() functions to detect 'NA' values.

In [33]:
df.isna().sum()

temperature    4
windspeed      4
event          2
dtype: int64

In [34]:
pd.isna(df["temperature"])

day
2017-01-01    False
2017-01-04     True
2017-01-05    False
2017-01-06     True
2017-01-07    False
2017-01-08     True
2017-01-09     True
2017-01-10    False
2017-01-11    False
Name: temperature, dtype: bool

In [35]:
pd.isna(df["windspeed"])

day
2017-01-01    False
2017-01-04    False
2017-01-05     True
2017-01-06    False
2017-01-07     True
2017-01-08     True
2017-01-09     True
2017-01-10    False
2017-01-11    False
Name: windspeed, dtype: bool

In [36]:
pd.notna(df["event"])

day
2017-01-01     True
2017-01-04     True
2017-01-05     True
2017-01-06    False
2017-01-07     True
2017-01-08     True
2017-01-09    False
2017-01-10     True
2017-01-11     True
Name: event, dtype: bool

## <font color="green"><h4>Handling Missing Data - fillna, interpolate, dropna</font>
<font color="green"><h2>Fillna</font>
    
<font color="green"><h3>Fill all NaN with one specific value</font>

In [37]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [38]:
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<font color="green"><h3>Fill specific Value in each column</font>

In [39]:
new_df = df.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'No Event'
    })
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  No Event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  No Event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

## <font color="green">**method to determine how to fill na values**</font>

In [40]:
new_df = df.fillna(method="ffill") # ffill used for forward fill
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [41]:
new_df = df.fillna(method="bfill") # bfill used for backward fill
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<font color="green">**Use of axis**</font>

In [42]:
new_df = df.fillna(method="bfill", axis="columns") # axis is either "index" or "columns"
new_df

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

<font color="green">**limit parameter**</font>

In [43]:
#by giving limit it will fill upto that limit value.
new_df = df.fillna(method="ffill",limit=1) 
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<font color="green"><h2>Dropna</font>

In [44]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [45]:
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

**how = 'all' or 'any'**

**tresh Number = Specifies the number of NULL values required to remove the row or column.**

In [46]:
new_df = df.dropna(how='all') # all used for removing all the row which contains atleast one null value
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [47]:
new_df = df.dropna(thresh=1) # it will not remove if the row have atleast one value filled.
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

### <font color="green">Inserting Missing Dates</font>

In [48]:
dt = pd.date_range("01-01-2017","01-11-2017")
idx = pd.DatetimeIndex(dt)
df.reindex(idx)

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## <font color="green"><h4>Handling Missing Data - replace method

In [49]:
df = pd.read_csv("weather_data_missing.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing single value**

In [50]:
new_df = df.replace(-99999, value=np.NaN)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

**Replacing list with single value**

In [51]:
new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing per column**

In [52]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

<font color="green"><h2>Indexing and slicing in pandas

Pandas provides three types of Multi-axes indexing. Those three types are mentioned in the following table:-

    1) .loc  - Label based

    2) .iloc - Integer based

    3) .ix   - Both Label and Integer based

.loc takes two single/list/range operator separated by ','.

The first one indicates the row and the second one indicates columns.

In [53]:
# select first row of dataframe
new_df.loc[0]

day            1/1/2017
temperature        32.0
windspeed           6.0
event              Rain
Name: 0, dtype: object

In [54]:
#select first five rows for a specific column
new_df.loc[:4,'event']

0     Rain
1    Sunny
2     Snow
3      NaN
4     Rain
Name: event, dtype: object

In [55]:
#Select all rows for multiple columns, say list[]

new_df.loc[:,['temperature','windspeed']]

   temperature  windspeed
0         32.0        6.0
1          NaN        7.0
2         28.0        NaN
3          NaN        7.0
4         32.0        NaN
5         31.0        2.0
6         34.0        5.0

Integer position based indexing using .iloc indexer

Pandas provides .iloc indexer for integer position based indexing.

In [56]:
new_df.iloc[0]

day            1/1/2017
temperature        32.0
windspeed           6.0
event              Rain
Name: 0, dtype: object

**Note :**

**.loc selects rows and columns with specific labels.**

**.iloc selects rows and columns at specific integer positions.**

In [57]:
# select last row of dataframe
new_df.iloc[-1]

day            1/6/2017
temperature        34.0
windspeed           5.0
event               NaN
Name: 6, dtype: object

In [58]:
# select 1st, 3rd and 5th rows with 1st, 2nd and 3rd columns

new_df.iloc[[0,2,5],[0,1,2]]

        day  temperature  windspeed
0  1/1/2017         32.0        6.0
2  1/3/2017         28.0        NaN
5  1/6/2017         31.0        2.0

## <font color="green"><h4>indexing

In [59]:
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

**Setting date as it's index**

In [60]:
new_df.set_index('day')

          temperature  windspeed  event
day
1/1/2017         32.0        6.0   Rain
1/2/2017          NaN        7.0  Sunny
1/3/2017         28.0        NaN   Snow
1/4/2017          NaN        7.0    NaN
1/5/2017         32.0        NaN   Rain
1/6/2017         31.0        2.0  Sunny
1/6/2017         34.0        5.0    NaN

**Reset index**

In [61]:
new_df.reset_index()

   index       day  temperature  windspeed  event
0      0  1/1/2017         32.0        6.0   Rain
1      1  1/2/2017          NaN        7.0  Sunny
2      2  1/3/2017         28.0        NaN   Snow
3      3  1/4/2017          NaN        7.0    NaN
4      4  1/5/2017         32.0        NaN   Rain
5      5  1/6/2017         31.0        2.0  Sunny
6      6  1/6/2017         34.0        5.0    NaN

## <font color="green"><h4>rename columns

**Method 1 – Pandas Rename**

pandas.DataFrame.rename(columns={"old_column_name" : "new_column_name"})

**Method 2 – Pandas .columns attribute**

pandas.DataFrame.columns = ['your', 'new', 'column', 'names']

**Method 3 – Pandas .set_axis(axis=1)**

pandas.DataFrame.set_axis(['your', 'new', 'column', 'names'2], axis=1)

In [62]:
DF = pd.DataFrame([('Foreign Cinema', 'Restaurant', 289.0),
                    ('Liho Liho', 'Restaurant', 224.0),
                    ('500 Club', 'bar', 80.5),
                    ('The Square', 'bar', 25.30)],
            columns=('name', 'type', 'AvgBill')
                  )
DF

             name        type  AvgBill
0  Foreign Cinema  Restaurant    289.0
1       Liho Liho  Restaurant    224.0
2        500 Club         bar     80.5
3      The Square         bar     25.3

In [63]:
DF.rename(columns = {'AvgBill': 'Bill'})

             name        type   Bill
0  Foreign Cinema  Restaurant  289.0
1       Liho Liho  Restaurant  224.0
2        500 Club         bar   80.5
3      The Square         bar   25.3

## <font color="green"><h4>Pandas Group By

In [1]:
import pandas as pd
df = pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [3]:
g = df.groupby("city")
g

**DataFrameGroupBy object looks something like below,**

<img src="group_by_cities.png">

In [66]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data:",data)

city: mumbai


data:         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
city: new york


data:         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
city: paris


data:          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [67]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [68]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [69]:
g.mean()

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

**This method of splitting your dataset in smaller groups and then applying an operation 
(such as min or max) to get aggregate result is called Split-Apply-Combine.**

**It is illustrated in a diagram below :**

<img src="split_apply_combine.png">

In [70]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

# <font color="green"><h4>Pandas Concatenate

## <font color='green'>Basic Concatenation</font>

In [71]:
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [72]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [73]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='green'>Concatenation And Keys</font>

In [74]:
df = pd.concat([india_weather, us_weather], keys=["india", "us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [75]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [76]:
df.loc["india"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

# <font color="green"><h4>Pandas Merge :
    
Pandas provides a single function "merge" as the entry point for all standard database join operations between DataFrame objects.

## <font color='green'>Basic Merge Using a Dataframe Column

In [77]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [78]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [79]:
df3 = pd.merge(df1, df2, on="city")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

**This is how we want to merge :**

<img src="join_image.jpg" width=550>

In [80]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [81]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0   new york         21.0      68.0
1    chicago         14.0      65.0
2    orlando         35.0       NaN
3  baltimore         38.0       NaN
4  san diego          NaN      71.0

In [82]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [83]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

## <font color="green"><h4>Extract unique value from the any column :

In [84]:
DF_1=pd.read_csv("Weather1.csv")
DF_1

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [85]:
DF_1["city"].unique()

array(['new york', 'mumbai', 'beijing'], dtype=object)

In [86]:
DF_1["temperature"].unique()

array([65, 66, 68, 75, 78, 82, 80, 77, 79], dtype=int64)